//auth
export const LOGIN = 'LOGIN'
export const REGISTRATION = 'REGISTRATION'
export const SET_TOKEN = 'SET_TOKEN'


//mainPage
export const GET_ROOM_LIST = 'GET_ROOM_LIST'

//chatRoom
export const GET_ROOM_USER_LIST = 'GET_ROOM_USER_LIST'
export const GET_ROOM_MESSAGE_LIST = 'GET_ROOM_MESSAGE_LIST'
export const GET_ROOM_DAILY_MESSAGE_LIST = 'GET_ROOM_DAILY_MESSAGE_LIST'
export const SEND_NEW_MESSAGE = 'SEND_NEW_MESSAGE'

