//auth
export const SET_UPDATING = 'SET_UPDATING'
export const SET_TOKEN = 'SET_TOKEN'

//mainPage
export const PUSH_MESSAGE_TO_MESSAGE_LIST = 'PUSH_MESSAGE_TO_MESSAGE_LIST'
export const SET_ROOMS_TO_ROOM_LIST = 'SET_ROOMS_TO_ROOM_LIST'

//chatRoom
export const SEND_NEW_MESSAGE = 'SEND_NEW_MESSAGE'
export const PUSH_DAILY_MESSAGE_TO_MESSAGE_LIST = 'PUSH_DAILY_MESSAGE_TO_MESSAGE_LIST'
